---
.travis.yml:
  script: "\"bundle exec rake validate lint spec SPEC_OPTS='--format documentation'\""
  includes:
  - rvm: 1.8.7
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 1.9.3
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0"
  - rvm: 2.1.5
    env: PUPPET_GEM_VERSION="~> 3.0" FUTURE_PARSER="yes"
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
Gemfile:
  required:
    ':development, :unit_tests':
      - gem: rspec-core
        version: '3.1.7'
      - gem: puppetlabs_spec_helper
      - gem: simplecov
      - gem: puppet_facts
      - gem: json
      - gem: metadata-json-lint
      - gem: puppet-blacksmith
    ':system_tests':
      - gem: beaker-rspec
        version: '*location_for(ENV["BEAKER_RSPEC_VERSION"])'
      - gem: beaker
        version: '*location_for(ENV["BEAKER_VERSION"])'
      - gem: serverspec
      - gem: beaker-puppet_install_helper
      - gem: master_manipulator
      - gem: beaker-hostgenerator
        version: '*location_for(ENV["BEAKER_VERSION"])'
Rakefile:
  default_disabled_lint_checks:
  - 'relative'
  - 'disable_80chars'
  - 'disable_class_inherits_from_params_class'
  - 'disable_documentation'
  - 'disable_single_quote_string_with_variables'
